kind: pipeline
name: default
trigger:
  branch:
    - main
  event:
    - push
steps:
- name: beardedtek-PUSH
  image: plugins/docker
  when:
    event:
      - push
  settings:
    username: beardedtek
    password:
      from_secret: docker_password
    repo: docker.beardedtek.com/beardedtek/nutui
    registry: docker.beardedtek.com
    tags: latest
    experimental: true
    compress: true
    squash: true