kind: pipeline
name: default
trigger:
  branch:
    - main
  event:
    - push
steps:
- name: beardedtek-PUSH
  image: plugins/docker
  when:
    event:
      - push
  settings:
    dockerfile: docker/Dockerfile
    username: beardedtek
    password:
      from_secret: dockerhub-token
    repo: beardedtek/nutui
    tags: latest
    experimental: true
    compress: true
    squash: true