#!/usr/bin/with-contenv bash
#    This code is a portion of nutUI
#
#    Copyright (C) 2021-2022  The Bearded Tek (http://www.beardedtek.com) William Kenny
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU AfferoGeneral Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
cd /nutui
source venv/bin/activate
uwsgi --http ${NUTUI_HOST:-0.0.0.0}:${NUTUI_PORT:-5000} --wsgi-file uwsgi.py --callable app --workers ${UWSGI_WORKERS:-4} --uid 1000 --gid 1000