#!/usr/bin/with-contenv bash
#    This code is a portion of nutUI
#
#    Copyright (C) 2021-2022  The Bearded Tek (http://www.beardedtek.com) William Kenny
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU AfferoGeneral Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
source /nutui/venv/bin/activate
CLA="-c -n ${NUT_HOST:-localhost}"
if [ -n "$NUTCLIENT_VERBOSE" ]; then
    CLA="$CLA -v"
fi
if [ -n "$NUTCLIENT_INTERVAL" ]; then
    CLA="$CLA -i $NUTCLIENT_INTERVAL"
fi
if [ -n "$NUTCLIENT_LOGIN" ]; then
    CLA="$CLA -l $NUTCLIENT_LOGIN"
fi
if [ -n "$NUTCLIENT_PASSWORD" ]; then
    CLA="$CLA -p $NUTCLIENT_PASSWORD"
fi

/nutui/nutui.py $CLA